project:
  type: website
  output-dir: docs

website:
  page-footer: "Copyright 2024, Felipe Antonio Dzul Manzanilla | Fabián Correa-Morales"
  title: "Análisis Espacial del Dengue en R"
  repo-url: https://github.com/fdzul/patial_analysis_dengue_R_2024-dev
  repo-actions: [edit, issue]
  favicon: imagenes/chains_ticul_2023.jpg
  twitter-card: true
  navbar:
    logo: imagenes/logo_curso_2024.png
    tools:
      - icon: twitter
        href: https://twitter.com/FdzulM
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - href: index.qmd
        text: Home
      - text: "Temario"
        href: temario.html
      - text: "Referencias"
        href: links.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
margin-header: |
  ![](imagenes/logo_curso_2024.png)

